import { copyFile } from "node:fs/promises";
import { builtinModules } from "node:module";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import tailwindcss from "@tailwindcss/vite";
import { defineConfig, type Plugin } from "vite";

function copyToRoot(rootDir: string, files: string[]): Plugin {
  return {
    name: "copy-to-root",
    async writeBundle(options) {
      const outDir = options.dir ?? dirname(options.file ?? "dist");
      for (const file of files) {
        await copyFile(resolve(outDir, file), resolve(rootDir, file));
      }
    },
  };
}

const __dirname = dirname(fileURLToPath(import.meta.url));

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY VITE
if you want to view the source, please visit the github repository of this plugin
*/
`;

export default defineConfig(({ mode }) => ({
  plugins: [tailwindcss(), copyToRoot(resolve(__dirname, ".."), ["main.js"])],
  build: {
    emptyOutDir: false,
    lib: {
      entry: resolve(__dirname, "src/main.ts"),
      formats: ["cjs"],
    },
    rollupOptions: {
      external: [
        "obsidian",
        "electron",
        "@codemirror/autocomplete",
        "@codemirror/collab",
        "@codemirror/commands",
        "@codemirror/language",
        "@codemirror/lint",
        "@codemirror/search",
        "@codemirror/state",
        "@codemirror/view",
        "@lezer/common",
        "@lezer/highlight",
        "@lezer/lr",
        ...builtinModules,
      ],
      output: {
        entryFileNames: "main.js",
        banner,
      },
    },
    target: "es2018",
    sourcemap: mode === "production" ? false : "inline",
    minify: mode === "production",
  },
}));
